In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [33]:
class TestAttention(keras.layers.Layer):
    '''
    input_dim = feature size = neuron number
    '''
    def __init__(self, input_dim=32):
        super().__init__()
        self.w = self.add_weight(
            shape=(input_dim, input_dim), initializer="random_normal", trainable=True
        )
        self.b = self.add_weight(shape=(input_dim,), initializer="zeros", trainable=True)

    def call(self, inputs):
        # Hadamard product
        product_x = tf.matmul(inputs, self.w) + self.b
        soft_x = tf.nn.softmax(product_x)
        output = tf.multiply(inputs, soft_x)
        return output
    def compute_mask(self, inputs, mask=None):
        return mask
    def get_config(self):
        config = super().get_config().copy()
        config.update({
            'con_layer': self.con_layer
        })
        return config

In [34]:
test_model = TestAttention(input_dim=20)

In [35]:
x = tf.ones(shape=(5, 4, 3, 20))

In [36]:
test_model(x)

<tf.Tensor: shape=(5, 4, 3, 20), dtype=float32, numpy=
array([[[[0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295],
         [0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295],
         [0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295]],

        [[0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295],
         [0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295],
         [0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295]],

        [[0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295],
         [0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295],
         [0.05740119, 0.06681139, 0.03939484, ..., 0.04144528,
          0.03300131, 0.04050295]],

        [[0.05740119, 0.06681139, 0.03939484, ..., 0.0414

In [37]:
np.diag(test_model.weights[0])

array([ 0.01237525,  0.06597295, -0.05451403,  0.09290468, -0.03517263,
        0.00183953, -0.03070671,  0.04293415,  0.1066607 ,  0.11968686,
       -0.04425209, -0.02062549,  0.04195477,  0.05131628,  0.01310358,
       -0.02710558,  0.03725766,  0.01898333, -0.0232844 ,  0.07396322],
      dtype=float32)